### PR TITLE
PHP 8.1 update

### PR DESCRIPTION
**Pull request by alexgit2k**
Core-features are working in PHP 8.1 with this update, some side-effects will be tackled in a later release by the maintainer.

See https://github.com/php/pecl-search_engine-solr/issues/27 and https://github.com/php/pecl-search_engine-solr/pull/30

### CODE REVIEW

**Comment by Jan-E** [comment]
@0mars @alexgit2k 
You are missing a couple of Windows fixes that were present in the issue-php8 branch of remi's repo: https://github.com/remicollet/pecl-search_engine-solr/commit/6eed1c59740742ba9ef57ea13a954ecebdfd5f5f

Adjusted for the other changes you made in the PR's:
```
diff --git a/config.w32 b/config.w32
index 1fa62fa..ea1bc3b 100644
--- a/config.w32
+++ b/config.w32
@@ -28,10 +28,8 @@ if(PHP_SOLR != 'no')
 		WARNING('solr was not enabled; IDN libraries (normaliz.lib) not found');
 		PHP_SOLR = "no";
 	}
-	if(!((CHECK_LIB('libssl.lib', 'solr', PHP_SOLR)
-		&& CHECK_LIB('libcrypto.lib', 'solr', PHP_SOLR)) ||
-		(CHECK_LIB('ssleay32.lib', 'solr', PHP_SOLR)
-		&& CHECK_LIB('libeay32.lib', 'solr', PHP_SOLR)))) {
+	if(!(CHECK_LIB('libssl.lib;ssleay32.lib', 'solr', PHP_SOLR)
+		&& CHECK_LIB('libcrypto.lib;libeay32.lib', 'solr', PHP_SOLR))) {
 		WARNING('solr was not enabled; openssl libraries not found');
 		PHP_SOLR = "no";
 	}
@@ -59,10 +57,6 @@ if(PHP_SOLR != 'no')
 			PHP_SOLR = "no";
 		}
 	}
-	if(PHP_JSON == 'no' || !ADD_EXTENSION_DEP('solr', 'json')) {
-		WARNING('solr was not enabled; json is not enabled');
-		PHP_SOLR = "no";
-	}
 	if(PHP_SOLR != 'no') {
 		if(PHP_SOLR_DEBUG == 'yes') {
 			AC_DEFINE('SOLR_DEBUG', 1, 'Solr debugging set to on');
@@ -75,13 +69,7 @@ if(PHP_SOLR != 'no')
 
         /* XXX tricky job here, override configure_module_dirname, define the basic extension,
             then set it back*/
-        if (null != dll.match(/^php5/)) {
-            configure_module_dirname = configure_module_dirname + "\\src\\php5";
-        } else if (null != dll.match(/^php7/)) {
-            configure_module_dirname = configure_module_dirname + "\\src\\php7";
-        } else {
-            ERROR("Cannot match any known PHP version with '" + dll + "'");
-        }
+		configure_module_dirname = configure_module_dirname + "\\src\\php7";
 
 		EXTENSION('solr',
 					'php_solr.c php_solr_client.c php_solr_document.c php_solr_exception.c ' +
diff --git a/pecl-compat/compat.h b/pecl-compat/compat.h
index c9c9ac5..003af2a 100644
--- a/pecl-compat/compat.h
+++ b/pecl-compat/compat.h
@@ -77,9 +77,13 @@
 #endif
 
 #ifdef PHP_WIN32
-#include <win32/php_stdint.h>
+#	if PHP_VERSION_ID < 80000
+#		include <win32/php_stdint.h>
+#	else
+#		include <inttypes.h>
+#	endif
 #else
-#include <inttypes.h>
+#	include <inttypes.h>
 #endif
 
 #if ZEND_EXTENSION_API_NO >= PHP_5_6_X_API_NO

```

**Comment by alexgit2k** [comment]
@Jan-E Remi provides only packages for RedHat Linux, probably therefore 6eed1c5 is also missing in the master-branch of the Remi-fork and never will be integrated here. You should push it to https://github.com/php/pecl-search_engine-solr

However, I am wondering why @remicollet hasn't pushed the other fixes to the original Solr-PECL-Repo?

**Comment by Jan-E** [comment]
@remicollet usually includes fixes for Windows as well, as long as they are Windows-only.

> However, I am wondering why @remicollet hasn't pushed the other fixes to the original Solr-PECL-Repo?

That is only something he can answer. Fact is that https://github.com/remicollet/pecl-search_engine-solr/tree/issue-php8 compiles for PHP 8.0.17 without problems on Windows and https://github.com/php/pecl-search_engine-solr fails on Windows for PHP 8.0.17, even with the additional patch:
```
php_solr.c
php_solr_client.c
php_solr_collapse_function.c
php_solr_dismax_query.c
ext\solr\src\php7\php_solr.c(102): error C2059: syntax error: 'constant'
ext\solr\src\php7\php_solr.c(103): error C2059: syntax error: '{'
ext\solr\src\php7\php_solr.c(150): error C2065: 'SolrDocument_current_args': undeclared identifier
ext\solr\src\php7\php_solr.c(151): error C2143: syntax error: missing ';' before '}'
ext\solr\src\php7\php_solr.c(153): error C2059: syntax error: 'constant'
ext\solr\src\php7\php_solr.c(154): error C2143: syntax error: missing '{' before '}'
ext\solr\src\php7\php_solr.c(154): error C2059: syntax error: '}'
ext\solr\src\php7\php_solr.c(177): error C2059: syntax error: 'constant'
ext\solr\src\php7\php_solr.c(177): error C2084: function 'int ZEND_BEGIN_ARG_WITH_TENTATIVE_RETURN_TYPE_INFO_EX()' already has a body
ext\solr\src\php7\php_solr.c(102): note: see previous definition of 'ZEND_BEGIN_ARG_WITH_TENTATIVE_RETURN_TYPE_INFO_EX'
```
Somthing goes wrong at https://github.com/php/pecl-search_engine-solr/blame/eb58118da1c9d50dcdbda5c17b271b8d07b703ea/src/php7/php_solr.c#L102 

For PHP 8.1 https://github.com/php/pecl-search_engine-solr with the additional patch compiles fine.

**Comment by remicollet** [comment]
> However, I am wondering why @remicollet hasn't pushed the other fixes to the original Solr-PECL-Repo?

Because I'm not the owner of this ext.

IIRC A major rewrite of serialization (using the 7.4 new API) is required for 8.1
(above my knowledge of Solr)

**Comment by alexgit2k** [comment]
> > However, I am wondering why @remicollet hasn't pushed the other fixes to the original Solr-PECL-Repo?
> 
> Because I'm not the owner of this ext.

I was talking about your commits to your branch [issue-php8](https://github.com/remicollet/pecl-search_engine-solr/commits/issue-php8). They are only merged in your repo, but not in the original repo (also not fully, because the one commit from Jan-E is missing). I don't think that owners of original repos are notified about changes in forks.

However, is there anything which prevents you from releasing a pecl-solr-rpm for PHP 8.1 now?
(Even if there are some side-effects accordingly to the owner, but the core-features are working)

**Comment by remicollet** [comment]
> However, is there anything which prevents you from releasing a pecl-solr-rpm for PHP 8.1 now?

Again "Because I'm not the owner of this ext."

What is not clear in this sentence ?

**Comment by remicollet** [comment]
Closing this PR, as this is not the right place to open it

**Comment by alexgit2k** [comment]
> > However, is there anything which prevents you from releasing a pecl-solr-rpm for PHP 8.1 now?
> 
> Again "Because I'm not the owner of this ext."
> 
> What is not clear in this sentence ?

Because that would mean, that each owner of a PHP-extension builds the RPMs for your Remi-repo.
I assumed that you build them yourself.

> Closing this PR, as this is not the right place to open it

Can you please help me, what to do next to get an 8.1 for solr at https://blog.remirepo.net/pages/PECL-extensions-RPM-status
Thanks.

**Comment by remicollet** [comment]
> I assumed that you build them yourself.

Yes, I build the RPM from upstream sources
WHEN a compatible version exists

And solr is not compatible (serialization is broken, test suite is failing with tons of "Deprecated")

PHP 8.1 compatibility have been tracked on https://github.com/remicollet/remirepo/issues/177

I often submit patches (see example in above issue) to help upstream projects.
But was not abe to do one for this one.

And upstream is aware of the problem

So, ask upstream on https://github.com/php/pecl-search_engine-solr/issues

This repo if only the fork I use to develop patches.

**Comment by remicollet** [comment]
to summarize

proper place for issue

- solr extrension: https://github.com/php/pecl-search_engine-solr/issues
- RPM packages in my repository: https://github.com/remicollet/remirepo/issues

**Comment by remicollet** [comment]
btw,  I have built the package for 8.1 (ignoring deprecation) and push it to the repo

reporting at the right place will have help to understand the real request ;)

**Comment by alexgit2k** [comment]
> This repo if only the fork I use to develop patches.

Ah, I thought you were building out from this fork. Therefore I created the PR to merge the latest version from upstream.

> And solr is not compatible (serialization is broken, test suite is failing with tons of "Deprecated")

It looks like you built the RPM from the latest release 2.5.1 from 2020, but not from master. With my patches to upstream there are no deprecations anymore and all core features are working (only 15 out of 151 tests fail which the author wants to address in a later version (https://github.com/php/pecl-search_engine-solr/issues/27#issuecomment-1067171025)).

Thank you very much.

**Pull request closed without merging**
